jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"sap/m/sample/Control_extension/project_29/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","sap/m/sample/Control_extension/project_29/model/models"],function(e,t,i){"use strict";return e.extend("sap.m.sample.Control_extension.project_29.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"sap/m/sample/Control_extension/project_29/CustomSwitch.js":function(){sap.ui.define(["sap/m/Switch","sap/m/SwitchRenderer"],function(e,t){"use strict";var e=e.extend("sap.m.sample.Control_extension.project_29.CustomSwitch",{renderer:t});e.prototype.onAfterRendering=function(){this.addStyleClass("myCustomSwt")};return e});
},
	"sap/m/sample/Control_extension/project_29/controller/Switch.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("sap.m.sample.Control_extension.project_29.controller.Switch",{onInit:function(){}})});
},
	"sap/m/sample/Control_extension/project_29/i18n/i18n.properties":'title=Extending controls\nappTitle=project_29\nappDescription=Extending controls',
	"sap/m/sample/Control_extension/project_29/i18n/i18n_ru.properties":'title=Ð Ð°ÑÑÐ¸ÑÐµÐ½Ð¸Ðµ ÑÐ»ÐµÐ¼ÐµÐ½ÑÐ¾Ð² ÑÐ¿ÑÐ°Ð²Ð»ÐµÐ½Ð¸Ñ\nappTitle=project_29\nappDescription=Ð Ð°ÑÑÐ¸ÑÐµÐ½Ð¸Ðµ ÑÐ»ÐµÐ¼ÐµÐ½ÑÐ¾Ð² ÑÐ¿ÑÐ°Ð²Ð»ÐµÐ½Ð¸Ñ',
	"sap/m/sample/Control_extension/project_29/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"sap.m.sample.Control_extension.project_29","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"sap.m.sample.Control_extension.project_29.view.Switch","type":"XML","async":true,"id":"Switch"},"dependencies":{"minUI5Version":"1.60.1","libs":{"sap.ui.layout":{},"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"sap.m.sample.Control_extension.project_29.i18n.i18n"}}},"resources":{"js":[{"uri":"CustomSwitch.js"}],"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"sap.m.sample.Control_extension.project_29.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteSwitch","pattern":"RouteSwitch","target":["TargetSwitch"]}],"targets":{"TargetSwitch":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"Switch","viewName":"Switch"}}}},"sap.platform.hcp":{"uri":"webapp","_version":"1.1.0"}}',
	"sap/m/sample/Control_extension/project_29/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"sap/m/sample/Control_extension/project_29/view/Switch.view.xml":'<mvc:View controllerName="sap.m.sample.Control_extension.project_29.controller.Switch"\n\txmlns:cust="sap.m.sample.Control_extension.project_29" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}"><subHeader><Toolbar><Switch state="false"/><cust:CustomSwitch state="true"/></Toolbar></subHeader><content></content></Page></pages></App></Shell></mvc:View>'
}});
